language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t travisci -f Dockerfile.dev .

script:
  - docker run -e CI=true travisci npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "travisci"
  env: "Travisci-env"
  bucket_name: "elasticbeanstalk-eu-central-1-250933953151"
  bucket_path: "travisci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
